{
  "language": "node_js",
  "node_js": [
    12
  ],
  "addons": {
    "chrome": "stable"
  },
  "before_script": [
    "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter",
    "chmod +x ./cc-test-reporter",
    "./cc-test-reporter before-build"
  ],
  "script": [
    "ng test --watch=false --browsers=ChromeHeadless --code-coverage"
  ],
  "after_script": [
    "./cc-test-reporter format-coverage -t lcov ./coverage/github-ngrx/lcov.info",
    "./cc-test-reporter upload-coverage"
  ],
  "notifications": {
    "email": false
  }
}
